"""Read and write Android string resources without losing order or section comments.

values/strings.xml is the source of truth; every values-<locale>/strings.xml is generated
from it. Generated files keep the source's order and its `<!-- Section -->` headings so a
diff between two locales lines up row for row.

Parsing is done with regexes rather than ElementTree on purpose: ElementTree would normalise
whitespace, drop the comments the sections are built from, and rewrite entity escapes we
want to control ourselves.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

_ENTRY_RE = re.compile(
    r"""<!--(?P<comment>.*?)-->"""
    r"""|<string\s+name="(?P<name>[^"]+)"(?P<attrs>[^>]*?)>(?P<body>.*?)</string>""",
    re.DOTALL,
)
_TRANSLATABLE_RE = re.compile(r'translatable\s*=\s*"false"')

HEADER = '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
FOOTER = "</resources>\n"


@dataclass
class StringRes:
    name: str
    text: str
    """Plain text: Android escaping already removed."""
    section: str
    translatable: bool = True


def _plain(raw: str) -> str:
    """Resource form -> plain text handed to the model."""
    out = raw.replace("\\'", "'").replace('\\"', '"').replace("\\@", "@").replace("\\?", "?")
    out = out.replace("\\n", "\n").replace("&amp;", "&")
    return out


def _escaped(text: str) -> str:
    """Plain text -> resource form. Inverse of `_plain`, applied on write.

    Only `&` is entity-escaped. `<` and `>` are left alone so inline markup (`<b>`, `<i>`)
    still works if a string ever needs it; the model is told to write plain text, and the
    validator flags stray angle brackets.
    """
    out = text.replace("&", "&amp;")
    out = out.replace("'", "\\'").replace('"', '\\"')
    out = out.replace("\n", "\\n")
    if out[:1] in ("@", "?"):
        out = "\\" + out
    return out


def _section_title(comment: str) -> str:
    """A comment block collapsed onto one line, which is what reads as a heading.

    Some headings carry a note explaining the section rather than just naming it; both are
    worth handing to a translator, so the whole comment is kept.
    """
    return " ".join(comment.split()).rstrip(".")


def read(path: Path) -> "list[StringRes]":
    if not path.exists():
        return []
    xml = path.read_text(encoding="utf-8")
    entries: list[StringRes] = []
    section = ""
    for match in _ENTRY_RE.finditer(xml):
        if match.group("comment") is not None:
            section = _section_title(match.group("comment"))
            continue
        entries.append(
            StringRes(
                name=match.group("name"),
                text=_plain(match.group("body")),
                section=section,
                translatable=not _TRANSLATABLE_RE.search(match.group("attrs") or ""),
            )
        )
    return entries


def write(path: Path, source: "list[StringRes]", translations: "dict[str, str]", locale: str) -> None:
    """Write a generated locale file, following `source` order and sections.

    Strings missing from `translations` are omitted rather than copied from English: an
    absent entry falls back to values/ at runtime, whereas an English copy sitting in
    values-de looks translated and never gets revisited.
    """
    lines = [
        HEADER.rstrip("\n"),
        f"    <!-- Generated by tools/i18n/translate.py for {locale}. Edit values/strings.xml,",
        "         or the review overrides, not this file. -->",
    ]
    section = None
    for entry in source:
        if entry.name not in translations:
            continue
        if entry.section != section:
            section = entry.section
            lines.append("")
            if section:
                lines.append(f"    <!-- {section} -->")
        lines.append(f'    <string name="{entry.name}">{_escaped(translations[entry.name])}</string>')
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + FOOTER, encoding="utf-8")
